package com.chiquitos11.veterinaria.view;

import com.chiquitos11.veterinaria.controller.ControllerBBDD;
import com.chiquitos11.veterinaria.enums.Gravedad;
import com.chiquitos11.veterinaria.enums.MotivoSalida;
import com.chiquitos11.veterinaria.enums.TipoAnimal;
import com.chiquitos11.veterinaria.model.Ave;

import java.sql.SQLException;
import java.time.LocalDate;

import java.util.logging.Level;
import java.util.logging.Logger;





/**
 *
 * @author ChiquitoS11
 */
public class Administracion extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    public Administracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // METER A CONTROLLERADMINISTRACION
    public void meow(){
        ControllerBBDD db = new ControllerBBDD();
        Ave a = new Ave("zxczxvzx", "KIKI", "curarle", LocalDate.now(), TipoAnimal.Ave, 13.23, Gravedad.HIGH, LocalDate.now(), MotivoSalida.MUERTE, "CARLOS", false);
        
        
        try {
            db.darAlta(a);
//            db.darAlta(new Reptil()); // ASI PASARE LOS DATOS DE LA LOGICA A LA ddbb
        } catch (SQLException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
