package com.chiquitos11.veterinaria.view;

import com.chiquitos11.veterinaria.controller.ControllerBBDD;
import com.chiquitos11.veterinaria.enums.Gravedad;
import com.chiquitos11.veterinaria.enums.TipoAnimal;
import com.chiquitos11.veterinaria.model.Ave;
import com.mysql.cj.jdbc.exceptions.CommunicationsException;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author ChiquitoS11
 */
public class Administracion extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public Administracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // METER A CONTROLLERADMINISTRACION
    public void meow(){
        ControllerBBDD db = new ControllerBBDD();
        Ave a = new Ave("zxczxvzx", "KIKI", "curarle", LocalDate.now(), TipoAnimal.Ave, 13.23, Gravedad.HIGH, false);
        
        
        try {
            db.darAlta(a);
         // db.darAlta(new Reptil()); // ASI PASARE LOS DATOS DE LA LOGICA A LA ddbb
        } catch (CommunicationsException e) {
            JOptionPane.showMessageDialog(null, "Error al conectar a la base de datos... Encienda el XAMPP");
        } catch (SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(null, "Un animal ya ha sido registrado con ese DNI, verifique los datos.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error desconocido, intentelo más tarde.");
            System.out.println("Error: " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
