package com.chiquitos11.veterinaria.view;

import com.chiquitos11.veterinaria.controller.ControllerBBDD;
import com.chiquitos11.veterinaria.deependency.UTILImagen;
import com.chiquitos11.veterinaria.enums.Gravedad;
import com.chiquitos11.veterinaria.enums.TipoAnimal;
import com.sun.tools.javac.Main;

/**
 *
 * @author ChiquitoS11
 */
public class Administracion extends javax.swing.JDialog {
    
    UTILImagen fp = new UTILImagen(Main.class.getClassLoader().getResource("fpMiku.gif"));
    UTILImagen logoIMG = new UTILImagen(Main.class.getClassLoader().getResource("rikka.png"));
    public UTILImagen altaIMG = new UTILImagen(Main.class.getClassLoader().getResource("inicio.gif"));
    public UTILImagen bajaIMG = new UTILImagen(Main.class.getClassLoader().getResource("monitaChinaLlorando.gif"));
    public UTILImagen liberacionIMG = new UTILImagen(Main.class.getClassLoader().getResource("gatoLiberacion.gif"));

    /**
     * Creates new form NewJDialog
     * @param parent
     * @param modal
     */
    public Administracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setContentPane(fp);
        initComponents();

        ajustesVisuales();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bajaJPANEL = new javax.swing.JPanel();
        animalActualJCB_BAJA = new javax.swing.JComboBox<>();
        mensajeUsuarioLABEL_BAJA = new javax.swing.JLabel();
        retrocederBTN_BAJA = new javax.swing.JButton();
        avanzarBTN_BAJA = new javax.swing.JButton();
        monitaChinaLABEL_BAJA = new javax.swing.JLabel();
        darBajaBTN_BAJA = new javax.swing.JButton();
        regresarMenuBTN_BAJA = new javax.swing.JButton();
        estadoBorradoLABEL_BAJA = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        veterinarioJTEXT_BAJA = new javax.swing.JTextField();
        altaJPANEL = new javax.swing.JPanel();
        dniLABEL = new javax.swing.JLabel();
        dniTEXTFIELD = new javax.swing.JTextField();
        nombreLABEL = new javax.swing.JLabel();
        nombreTEXTFIELD = new javax.swing.JTextField();
        pesoLABEL = new javax.swing.JLabel();
        gravedadLABEL = new javax.swing.JLabel();
        motivoLesionLABEL = new javax.swing.JLabel();
        motivoLesionJCHECK_ALTA = new javax.swing.JCheckBox();
        monitaChinaLABELalta = new javax.swing.JLabel();
        pesoLABEL1 = new javax.swing.JLabel();
        especieJCB = new javax.swing.JComboBox<>();
        gravedadJCB = new javax.swing.JComboBox<>();
        pesoJSPINNER_ALTA = new javax.swing.JSpinner();
        enviarBTN_ALTA = new javax.swing.JButton();
        regresarMenuBTN_ALTA = new javax.swing.JButton();
        mensajeFechaLABEL = new javax.swing.JLabel();
        estadoSubidaLABEL = new javax.swing.JLabel();
        tratamientoJPANEL = new javax.swing.JPanel();
        liberacionJPANEL = new javax.swing.JPanel();
        darBajaBTN_LIBERACION = new javax.swing.JButton();
        regresarMenuBTN_LIBERACION = new javax.swing.JButton();
        estadoBorradoLABEL_LIBERACION = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        veterinarioJTEXT_LIBERACION = new javax.swing.JTextField();
        animalActualJCB_LIBERACION = new javax.swing.JComboBox<>();
        mensajeUsuarioLABEL_LIBERACION = new javax.swing.JLabel();
        retrocederBTN_LIBERACION = new javax.swing.JButton();
        avanzarBTN_LIBERACION = new javax.swing.JButton();
        monitaChinaLABEL_LIBERACION = new javax.swing.JLabel();
        listadoJPANEL = new javax.swing.JPanel();
        logoLABEL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuJPANEL = new javax.swing.JPanel();
        inicioJPANEL = new javax.swing.JPanel();
        altaBTN = new javax.swing.JButton();
        tratamientoBTN = new javax.swing.JButton();
        listadoBTN = new javax.swing.JButton();
        bajaBTN = new javax.swing.JButton();
        liberacionBTN = new javax.swing.JButton();
        salirBTN = new javax.swing.JButton();
        menuMonitaLABEL = new javax.swing.JLabel();

        bajaJPANEL.setOpaque(false);

        animalActualJCB_BAJA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalActualJCB_BAJAActionPerformed(evt);
            }
        });

        mensajeUsuarioLABEL_BAJA.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        mensajeUsuarioLABEL_BAJA.setForeground(new java.awt.Color(0, 0, 0));
        mensajeUsuarioLABEL_BAJA.setText("¿Qué tipo de animal desea dar de baja?");

        retrocederBTN_BAJA.setText("Atrás");
        retrocederBTN_BAJA.setEnabled(false);
        retrocederBTN_BAJA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrocederBTN_BAJAActionPerformed(evt);
            }
        });

        avanzarBTN_BAJA.setText("Adelante");

        darBajaBTN_BAJA.setText("Dar Baja");
        darBajaBTN_BAJA.setEnabled(false);

        regresarMenuBTN_BAJA.setText("Regresar");

        estadoBorradoLABEL_BAJA.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        estadoBorradoLABEL_BAJA.setForeground(new java.awt.Color(255, 102, 102));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Veterinario a Cargo:");

        veterinarioJTEXT_BAJA.setEnabled(false);
        veterinarioJTEXT_BAJA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veterinarioJTEXT_BAJAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bajaJPANELLayout = new javax.swing.GroupLayout(bajaJPANEL);
        bajaJPANEL.setLayout(bajaJPANELLayout);
        bajaJPANELLayout.setHorizontalGroup(
            bajaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bajaJPANELLayout.createSequentialGroup()
                .addGroup(bajaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bajaJPANELLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(retrocederBTN_BAJA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(avanzarBTN_BAJA)
                        .addGap(125, 125, 125))
                    .addGroup(bajaJPANELLayout.createSequentialGroup()
                        .addGroup(bajaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bajaJPANELLayout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addGroup(bajaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estadoBorradoLABEL_BAJA, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mensajeUsuarioLABEL_BAJA, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(bajaJPANELLayout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(animalActualJCB_BAJA, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bajaJPANELLayout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veterinarioJTEXT_BAJA, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bajaJPANELLayout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(darBajaBTN_BAJA)))
                        .addGap(107, 126, Short.MAX_VALUE)))
                .addComponent(monitaChinaLABEL_BAJA, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bajaJPANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regresarMenuBTN_BAJA)
                .addGap(331, 331, 331))
        );
        bajaJPANELLayout.setVerticalGroup(
            bajaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bajaJPANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mensajeUsuarioLABEL_BAJA)
                .addGap(42, 42, 42)
                .addComponent(animalActualJCB_BAJA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(bajaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(veterinarioJTEXT_BAJA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bajaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retrocederBTN_BAJA)
                    .addComponent(avanzarBTN_BAJA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(darBajaBTN_BAJA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estadoBorradoLABEL_BAJA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(bajaJPANELLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(monitaChinaLABEL_BAJA, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(regresarMenuBTN_BAJA)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        altaJPANEL.setOpaque(false);

        dniLABEL.setForeground(new java.awt.Color(0, 0, 0));
        dniLABEL.setText("DNI:");

        nombreLABEL.setForeground(new java.awt.Color(0, 0, 0));
        nombreLABEL.setText("Nombre:");

        pesoLABEL.setForeground(new java.awt.Color(0, 0, 0));
        pesoLABEL.setText("Peso:");

        gravedadLABEL.setForeground(new java.awt.Color(0, 0, 0));
        gravedadLABEL.setText("Gravedad:");

        motivoLesionLABEL.setForeground(new java.awt.Color(0, 0, 0));
        motivoLesionLABEL.setText("Caza Furtiva ?");

        pesoLABEL1.setForeground(new java.awt.Color(0, 0, 0));
        pesoLABEL1.setText("Especie:");

        especieJCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especieJCBActionPerformed(evt);
            }
        });

        gravedadJCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravedadJCBActionPerformed(evt);
            }
        });

        pesoJSPINNER_ALTA.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));
        pesoJSPINNER_ALTA.setEditor(new javax.swing.JSpinner.DefaultEditor(pesoJSPINNER_ALTA));

        enviarBTN_ALTA.setText("Dar el Alta");
        enviarBTN_ALTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarBTN_ALTAActionPerformed(evt);
            }
        });

        regresarMenuBTN_ALTA.setText("Regresar");

        mensajeFechaLABEL.setForeground(new java.awt.Color(0, 0, 0));
        mensajeFechaLABEL.setText("(El tiempo será tomado automaticamente al ser dado de alta :D)");

        estadoSubidaLABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        estadoSubidaLABEL.setForeground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout altaJPANELLayout = new javax.swing.GroupLayout(altaJPANEL);
        altaJPANEL.setLayout(altaJPANELLayout);
        altaJPANELLayout.setHorizontalGroup(
            altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altaJPANELLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(altaJPANELLayout.createSequentialGroup()
                        .addComponent(motivoLesionLABEL)
                        .addGap(28, 28, 28)
                        .addComponent(motivoLesionJCHECK_ALTA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, altaJPANELLayout.createSequentialGroup()
                            .addComponent(gravedadLABEL)
                            .addGap(43, 43, 43)
                            .addComponent(gravedadJCB, 0, 145, Short.MAX_VALUE))
                        .addGroup(altaJPANELLayout.createSequentialGroup()
                            .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, altaJPANELLayout.createSequentialGroup()
                                        .addComponent(dniLABEL)
                                        .addGap(73, 73, 73))
                                    .addGroup(altaJPANELLayout.createSequentialGroup()
                                        .addComponent(nombreLABEL)
                                        .addGap(49, 49, 49)))
                                .addGroup(altaJPANELLayout.createSequentialGroup()
                                    .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pesoLABEL1)
                                        .addComponent(pesoLABEL))
                                    .addGap(54, 54, 54)))
                            .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pesoJSPINNER_ALTA, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dniTEXTFIELD)
                                    .addComponent(nombreTEXTFIELD)
                                    .addComponent(especieJCB, 0, 145, Short.MAX_VALUE)))))
                    .addComponent(mensajeFechaLABEL)
                    .addGroup(altaJPANELLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(regresarMenuBTN_ALTA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enviarBTN_ALTA))
                    .addComponent(estadoSubidaLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(monitaChinaLABELalta, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        altaJPANELLayout.setVerticalGroup(
            altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altaJPANELLayout.createSequentialGroup()
                .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(altaJPANELLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dniLABEL)
                            .addComponent(dniTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreLABEL)
                            .addComponent(nombreTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesoLABEL1)
                            .addComponent(especieJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(mensajeFechaLABEL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesoLABEL)
                            .addComponent(pesoJSPINNER_ALTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gravedadJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gravedadLABEL))
                        .addGap(28, 28, 28)
                        .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motivoLesionLABEL)
                            .addComponent(motivoLesionJCHECK_ALTA, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(altaJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enviarBTN_ALTA)
                            .addComponent(regresarMenuBTN_ALTA)))
                    .addGroup(altaJPANELLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(monitaChinaLABELalta, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(estadoSubidaLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        regresarMenuBTN_ALTA.getAccessibleContext().setAccessibleDescription("");

        tratamientoJPANEL.setOpaque(false);

        javax.swing.GroupLayout tratamientoJPANELLayout = new javax.swing.GroupLayout(tratamientoJPANEL);
        tratamientoJPANEL.setLayout(tratamientoJPANELLayout);
        tratamientoJPANELLayout.setHorizontalGroup(
            tratamientoJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        tratamientoJPANELLayout.setVerticalGroup(
            tratamientoJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        liberacionJPANEL.setOpaque(false);

        darBajaBTN_LIBERACION.setText("Dar Baja");
        darBajaBTN_LIBERACION.setEnabled(false);

        regresarMenuBTN_LIBERACION.setText("Regresar");

        estadoBorradoLABEL_LIBERACION.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        estadoBorradoLABEL_LIBERACION.setForeground(new java.awt.Color(255, 102, 102));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Veterinario a Cargo:");

        veterinarioJTEXT_LIBERACION.setEnabled(false);

        mensajeUsuarioLABEL_LIBERACION.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        mensajeUsuarioLABEL_LIBERACION.setForeground(new java.awt.Color(0, 0, 0));
        mensajeUsuarioLABEL_LIBERACION.setText("¿Qué tipo de animal desea dar en libertad?");

        retrocederBTN_LIBERACION.setText("Atrás");
        retrocederBTN_LIBERACION.setEnabled(false);

        avanzarBTN_LIBERACION.setText("Adelante");

        javax.swing.GroupLayout liberacionJPANELLayout = new javax.swing.GroupLayout(liberacionJPANEL);
        liberacionJPANEL.setLayout(liberacionJPANELLayout);
        liberacionJPANELLayout.setHorizontalGroup(
            liberacionJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liberacionJPANELLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(liberacionJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(liberacionJPANELLayout.createSequentialGroup()
                        .addGroup(liberacionJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(liberacionJPANELLayout.createSequentialGroup()
                                .addComponent(retrocederBTN_LIBERACION)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(avanzarBTN_LIBERACION)
                                .addGap(125, 125, 125))
                            .addGroup(liberacionJPANELLayout.createSequentialGroup()
                                .addGroup(liberacionJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(liberacionJPANELLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(liberacionJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(estadoBorradoLABEL_LIBERACION, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mensajeUsuarioLABEL_LIBERACION, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(liberacionJPANELLayout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(animalActualJCB_LIBERACION, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(liberacionJPANELLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(veterinarioJTEXT_LIBERACION, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(liberacionJPANELLayout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(darBajaBTN_LIBERACION)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(monitaChinaLABEL_LIBERACION, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, liberacionJPANELLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(regresarMenuBTN_LIBERACION)
                        .addGap(259, 259, 259)))
                .addGap(71, 71, 71))
        );
        liberacionJPANELLayout.setVerticalGroup(
            liberacionJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liberacionJPANELLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(liberacionJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(liberacionJPANELLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mensajeUsuarioLABEL_LIBERACION)
                        .addGap(42, 42, 42)
                        .addComponent(animalActualJCB_LIBERACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(liberacionJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(veterinarioJTEXT_LIBERACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(liberacionJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(retrocederBTN_LIBERACION)
                            .addComponent(avanzarBTN_LIBERACION))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(darBajaBTN_LIBERACION)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(estadoBorradoLABEL_LIBERACION, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(liberacionJPANELLayout.createSequentialGroup()
                        .addComponent(monitaChinaLABEL_LIBERACION, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(regresarMenuBTN_LIBERACION)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        listadoJPANEL.setOpaque(false);

        javax.swing.GroupLayout listadoJPANELLayout = new javax.swing.GroupLayout(listadoJPANEL);
        listadoJPANEL.setLayout(listadoJPANELLayout);
        listadoJPANELLayout.setHorizontalGroup(
            listadoJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        listadoJPANELLayout.setVerticalGroup(
            listadoJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        logoLABEL.setBackground(new java.awt.Color(51, 255, 102));
        logoLABEL.setForeground(new java.awt.Color(51, 255, 0));

        jLabel1.setBackground(new java.awt.Color(51, 51, 0));
        jLabel1.setFont(new java.awt.Font("Cascadia Code", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("VETERINARIA");

        jLabel2.setBackground(new java.awt.Color(51, 51, 0));
        jLabel2.setFont(new java.awt.Font("Cascadia Code", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("NICOLINI");

        menuJPANEL.setOpaque(false);

        inicioJPANEL.setOpaque(false);

        altaBTN.setText("ALTA");
        altaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaBTNActionPerformed(evt);
            }
        });

        tratamientoBTN.setText("TRATAMIENTO");

        listadoBTN.setText("LISTADO");

        bajaBTN.setText("BAJA");

        liberacionBTN.setText("LIBERACION");

        salirBTN.setText("SALIR");

        javax.swing.GroupLayout inicioJPANELLayout = new javax.swing.GroupLayout(inicioJPANEL);
        inicioJPANEL.setLayout(inicioJPANELLayout);
        inicioJPANELLayout.setHorizontalGroup(
            inicioJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioJPANELLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(inicioJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tratamientoBTN)
                    .addGroup(inicioJPANELLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(bajaBTN)))
                .addGap(34, 34, 34)
                .addComponent(menuMonitaLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(inicioJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(liberacionBTN)
                    .addGroup(inicioJPANELLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(listadoBTN)))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioJPANELLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(inicioJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salirBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(altaBTN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(373, 373, 373))
        );
        inicioJPANELLayout.setVerticalGroup(
            inicioJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioJPANELLayout.createSequentialGroup()
                .addGroup(inicioJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicioJPANELLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(inicioJPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inicioJPANELLayout.createSequentialGroup()
                                .addComponent(listadoBTN)
                                .addGap(92, 92, 92)
                                .addComponent(liberacionBTN))
                            .addGroup(inicioJPANELLayout.createSequentialGroup()
                                .addComponent(tratamientoBTN)
                                .addGap(92, 92, 92)
                                .addComponent(bajaBTN))))
                    .addGroup(inicioJPANELLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(altaBTN)
                        .addGap(18, 18, 18)
                        .addComponent(menuMonitaLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(salirBTN)
                .addGap(61, 61, 61))
        );

        menuJPANEL.add(inicioJPANEL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(47, 47, 47))
            .addComponent(menuJPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuJPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaBTNActionPerformed


    }//GEN-LAST:event_altaBTNActionPerformed

    private void gravedadJCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravedadJCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gravedadJCBActionPerformed

    private void enviarBTN_ALTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarBTN_ALTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarBTN_ALTAActionPerformed

    private void especieJCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especieJCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especieJCBActionPerformed

    private void animalActualJCB_BAJAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalActualJCB_BAJAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalActualJCB_BAJAActionPerformed

    private void retrocederBTN_BAJAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrocederBTN_BAJAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retrocederBTN_BAJAActionPerformed

    private void veterinarioJTEXT_BAJAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veterinarioJTEXT_BAJAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veterinarioJTEXT_BAJAActionPerformed
    
    
    
    public void ajustesVisuales() {
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        
        
        for (TipoAnimal tipoAni : TipoAnimal.values()) {
            especieJCB.addItem(tipoAni);
        }
        
        for (Gravedad grav : Gravedad.values()) {
            gravedadJCB.addItem(grav);
        }
        
        
        
        logoIMG.imgToContainer(logoLABEL);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton altaBTN;
    public javax.swing.JPanel altaJPANEL;
    public javax.swing.JComboBox<String> animalActualJCB_BAJA;
    public javax.swing.JComboBox<String> animalActualJCB_LIBERACION;
    public javax.swing.JButton avanzarBTN_BAJA;
    public javax.swing.JButton avanzarBTN_LIBERACION;
    public javax.swing.JButton bajaBTN;
    public javax.swing.JPanel bajaJPANEL;
    public javax.swing.JButton darBajaBTN_BAJA;
    public javax.swing.JButton darBajaBTN_LIBERACION;
    private javax.swing.JLabel dniLABEL;
    public javax.swing.JTextField dniTEXTFIELD;
    public javax.swing.JButton enviarBTN_ALTA;
    public javax.swing.JComboBox<TipoAnimal> especieJCB;
    public javax.swing.JLabel estadoBorradoLABEL_BAJA;
    public javax.swing.JLabel estadoBorradoLABEL_LIBERACION;
    public javax.swing.JLabel estadoSubidaLABEL;
    public javax.swing.JComboBox<Gravedad> gravedadJCB;
    private javax.swing.JLabel gravedadLABEL;
    public javax.swing.JPanel inicioJPANEL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JButton liberacionBTN;
    public javax.swing.JPanel liberacionJPANEL;
    public javax.swing.JButton listadoBTN;
    public javax.swing.JPanel listadoJPANEL;
    private javax.swing.JLabel logoLABEL;
    private javax.swing.JLabel mensajeFechaLABEL;
    private javax.swing.JLabel mensajeUsuarioLABEL_BAJA;
    private javax.swing.JLabel mensajeUsuarioLABEL_LIBERACION;
    public javax.swing.JPanel menuJPANEL;
    private javax.swing.JLabel menuMonitaLABEL;
    public javax.swing.JLabel monitaChinaLABEL_BAJA;
    public javax.swing.JLabel monitaChinaLABEL_LIBERACION;
    public javax.swing.JLabel monitaChinaLABELalta;
    public javax.swing.JCheckBox motivoLesionJCHECK_ALTA;
    public javax.swing.JLabel motivoLesionLABEL;
    private javax.swing.JLabel nombreLABEL;
    public javax.swing.JTextField nombreTEXTFIELD;
    public javax.swing.JSpinner pesoJSPINNER_ALTA;
    private javax.swing.JLabel pesoLABEL;
    private javax.swing.JLabel pesoLABEL1;
    public javax.swing.JButton regresarMenuBTN_ALTA;
    public javax.swing.JButton regresarMenuBTN_BAJA;
    public javax.swing.JButton regresarMenuBTN_LIBERACION;
    public javax.swing.JButton retrocederBTN_BAJA;
    public javax.swing.JButton retrocederBTN_LIBERACION;
    public javax.swing.JButton salirBTN;
    public javax.swing.JButton tratamientoBTN;
    public javax.swing.JPanel tratamientoJPANEL;
    public javax.swing.JTextField veterinarioJTEXT_BAJA;
    public javax.swing.JTextField veterinarioJTEXT_LIBERACION;
    // End of variables declaration//GEN-END:variables
}
