package com.chiquitos11.veterinaria.view;

import com.chiquitos11.veterinaria.controller.ControllerVeterinaria;
import com.chiquitos11.veterinaria.model.UTILPersonaje;
import com.chiquitos11.veterinaria.model.UTILImagen;

/**
 *
 * @author ChiquitoS11
 */
public class Veterinaria extends javax.swing.JFrame {

    UTILPersonaje personajePERSONAJE;
    UTILImagen fp = new UTILImagen(getClass().getResource("/resources/CentroPokemon.jpeg"));
    UTILImagen IMGpersonaje = new UTILImagen(getClass().getResource("/resources/static.png"));
    
    /**
     * Creates new form Veterinaria
     */
    public Veterinaria() {
        this.setContentPane(fp);
        initComponents();
        ajustesVisuales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personajeLABEL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(personajeLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(504, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(personajeLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel personajeLABEL;
    // End of variables declaration//GEN-END:variables
    private void ajustesVisuales() {
        personajeLABEL.setIcon(IMGpersonaje.imgToContainer(personajeLABEL));
    }
}
